version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: barbershop-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}

  server:
    build: ./server
    container_name: barbershop-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env.production

  client:
    build: ./client
    container_name: barbershop-client
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - server
    env_file:
      - .env.production

volumes:
  mongo_data:

